In [16]:
import numpy as np
import pandas as pd

In [17]:
messages = pd.read_csv("/content/spam_ham_dataset.csv",index_col=0)
messages.head()

     label                                               text  label_num
605    ham  Subject: enron methanol ; meter # : 988291\r\n...          0
2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0
3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0
4685  spam  Subject: photoshop , windows , office . cheap ...          1
2030   ham  Subject: re : indian springs\r\nthis deal is t...          0

In [18]:
messages.drop("label_num",axis=1,inplace=True)
messages.head()

     label                                               text
605    ham  Subject: enron methanol ; meter # : 988291\r\n...
2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...
3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...
4685  spam  Subject: photoshop , windows , office . cheap ...
2030   ham  Subject: re : indian springs\r\nthis deal is t...

In [19]:
messages.reset_index(drop=True,inplace=True)

In [20]:
messages.head()

  label                                               text
0   ham  Subject: enron methanol ; meter # : 988291\r\n...
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...
3  spam  Subject: photoshop , windows , office . cheap ...
4   ham  Subject: re : indian springs\r\nthis deal is t...

In [23]:
messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   5171 non-null   object
 1   text    5171 non-null   object
dtypes: object(2)
memory usage: 80.9+ KB

In [24]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
Lemmatizer = WordNetLemmatizer()
import re

In [27]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [28]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub("[^a-zA-Z]"," ",messages["text"][i])
    review = review.lower()
    review = review.split()
    review = [Lemmatizer.lemmatize(word) for word in review if not word in stopwords.words("english")]
    review = " ".join(review)
    corpus.append(review)

In [29]:
corpus

['subject enron methanol meter follow note gave monday preliminary flow data provided daren please override pop daily volume presently zero reflect daily activity obtain gas control change needed asap economics purpose',
 'subject hpl nom january see attached file hplnol xl hplnol xl',
 'subject neon retreat ho ho ho around wonderful time year neon leader retreat time know time year extremely hectic tough think anything past holiday life go past week december january like think minute calender handed beginning fall semester retreat scheduled weekend january youth minister conference brad dustin connected week going change date following weekend january come part need think think agree important u get together time recharge battery get far spring semester lot trouble difficult u get away without kid etc brad came potential alternative get together weekend let know prefer first option would retreat similar done past several year year could go heartland country inn www com outside brenham nice place bedroom bedroom house side side country real relaxing also close brenham one hour minute golf shop antique craft store brenham eat dinner together ranch spend time meet saturday return sunday morning like done past second option would stay houston dinner together nice restaurant dessert time visiting recharging one home saturday evening might easier trade would much time together let decide email back would preference course available weekend democratic process prevail majority vote rule let hear soon possible preferably end weekend vote go way complaining allowed like tend great weekend great golf great fishing great shopping whatever make happy bobby',
 'subject photoshop window office cheap main trending abasement darer prudently fortuitous undergone lighthearted charm orinoco taster railroad affluent pornographic cuvier irvin parkhouse blameworthy chlorophyll robed diagrammatic fogarty clear bayda inconveniencing managing represented smartness hashish academy shareholder unload badness danielson pure caffein spaniard chargeable levin',
 'subject indian spring deal book teco pvr revenue understanding teco sends u check received answer whether predermined price associated deal teco let u know giving continue chase deal need',
 'subject ehronline web address change message intended ehronline user due recent change ehronline url aka web address accessing ehronline need changed computer change involves adding letter http reference url url accessing ehronline http ehronline enron com change made added url favorite browser',
 'subject spring saving certificate take save use customer appreciation spring saving certificate foot locker lady foot locker kid foot locker online store welcome customer appreciation spring saving certificate use special certificate receive purchase either store online hurry day sale begin thursday march end sunday march share saving today e mail offer friend many item already reduced discount taken lowest sale price click print customer appreciation spring saving certificate must present coupon foot locker lady foot locker kid foot locker store u foot locker canada participating program ready set save spring saving discount automatically appear use link type camlem promotion code box checkout footlocker com certificate code camlem ladyfootlocker com certificate code camlem kidsfootlocker com certificate code camlem remember return hassle free simply bring item store nationwide mail left register today learn new product promotion event special simply click term condition exclusion apply please see manager complete detail certificate must presented time purchase cannot used conjunction discount offer associate benefit redeemable cash applicable tax must paid bearer cannot applied prior purchase gift card purchase void prohibited licensed regulated catalog exclusion apply valid thursday sunday foot locker canada participate program wish receive future email please click unsubscribe',
 'subject looking medication best source difficult make material condition better best law easy enough ruin bad law excuse found best simpliest site medication net perscription easy delivery private secure easy better see rightly pound week squint million got anything ever want erection treatment pill anti depressant pill weight loss http splicing bombahakcx com knowledge human power synonymous high quality stuff low rate moneyback guarantee god nature sufficeth unto wise hath need author',
 'subject noms actual flow agree forwarded melissa jones texas utility eileen ponton david avila lsp enserch u tu charlie stone texas utility tu melissa jones texas utility tu hpl scheduling enron com liz bellamy enron com cc subject noms actual flow date nom flow mcf flow mmbtu btu',
 'subject nomination oct see attached file hplnl xl hplnl xl',
 'subject vocable rnd word asceticism vcsc brand new stock attention vocalscape inc stock symbol vcsc vcsc top stock pick month april stock expected bounce cent level stock hit time low bounce back stock going explode next day watch soar watch stock go crazy next week breaking news vocalscape inc announces agreement resell mix network service current price expect projected speculative price next day expect projected speculative price next day vocalscape network inc building company revolutionizing telecommunication industry affordable phone system hardware online software rate canada u vocalscape company global reach receiving international attention development voice ip voip application solution including award winning eyefontm softphone real time pc phone advanced implementer pbx system company call center itsps service provider vocalscape created software interactive solution revolving around global communication data voice convergence company use vocalscape voice internet protocol application like ip pbxs softswitches pc phone web phone providing real time human interaction information delivery internet vocalscape solution business offer quality voice service anywhere world rate significantly lower current long distance charge develop software run voip network sell install service branded voip gateway gatekeeper control software also license software customer want brand voip solution vocalscape committed making great technology challenging status quo building st century company change way business communicate interact internet current price expect projected speculative price next day expect projected speculative price next day breaking news vocalscape inc announces agreement resell mix network service katonah n prnewswire firstcall via comtex vocalscape inc pink vcsc emerging leader development voice internet protocol voip telephony solution announced today entered sale agent agreement mix network inc voip enhanced telephony service provider agreement provides vocalscape turnkey calling card customer access mix network service including north american dids phone number domestic long distance termination vocalscape also able supply client enhanced voip product including pre paid calling mix network north american network excited help company launch voip business model using solution whole picture software network needed route call mix network give u ability offer wholesale monthly flat rate plan dids client allow u build business model like popular voip company vonage packet say ryan gibson vp vocalscape network legal word continue information within email contains forward looking statement within meaning section security act section b security exchange act statement express involve discussion respect prediction goal expectation belief plan projection objective assumption future event performance statement historical fact may forward looking statement forward looking statement based expectation estimate projection time statement made involve number risk uncertainty could cause actual result event differ materially presently anticipated forward looking statement action may identified use word project foresee expects estimate belief understands part anticipates statement indicating certain action may could might occur information provided within email pertaining investing stock security must understood information provided investment advice emerging equity alert advises reader subscriber seek advice registered professional security representative deciding trade stock featured within email none material within report shall construed kind investment advice please mind interpretation witer newsletter news published company represent company official statement fact may differ real meaning news release meant say look news release judge detail compliance section b disclose holding vcsc share prior publication report aware inherent conflict interest resulting holding due intent profit liquidation share share may sold time even positive statement made regarding company since share inherent conflict interest statement opinion reader publication cautioned place undue reliance forward looking statement based certain assumption expectation involving various risk uncertainty could cause result differ materially set forth forward looking statement please advised nothing within email shall constitute solicitation invitation get position sell security mentioned herein newsletter neither registered investment advisor affiliated broker dealer newsletter paid third party send report statement made express opinion treated may take position sell security mentioned time report includes forward looking statement within meaning private security litigation reform act statement may include term projected speculative price expect believe may soar move undervalued intend similar term',
 'subject report wffur attion brom est inst siupied pgst riwe asently rest tont presyou tew con benco yee fater ust lyughtatums inenced sorepit grathers aicy graghteave allarity oarity wow yur coon mers oite ithat yoit berst thar enth excives',
 'subject enron hpl actuals august teco tap enron hpl gas daily l hpl lsk ic enron',
 'subject vic odin n ow berne hotbox carnal bride cutworm dyadic guardia continuous born gremlin akin counterflow hereafter vocabularian pessimum yaounde cannel bitch penetrate demagogue arbitrary egregious adenosine rubin gil luminosity delicti yarmulke sauterne selfadjoint agleam exeter picofarad consulate dichotomous boyhood balfour spheric frey pillory hoosier fibonacci cat handful',
 'subject tenaska iv july darren please remove price tenaska iv sale deal july enter demand fee amount thanks megan',
 'subject underpriced issue high return equity stock report dont sieep stock hot one company gaming transaction inc stock symbol ggts currentiy trading rating strong purchase near term target long term target oo breaking news ggts gaming transaction inc ggts eading provider online gaming porta management pleased announce launched proprietary gaming portal k e n com furthermore company begun intensive marketing campaign support aunch establish eader online gaming industry k e n c oniine game destination people piay popular casino style game win real money foundation site online version keno game keno us ball numbered thru every game house draw bail random display number screen called keno board located website object game player guess number house draw site shall also popuiar game near future inciuding bingo poker blackjack slot video game version tabie game patrick smyth ceo gaming transaction inc remarked game deveioped foresight create user friendly experience without loading time secure transaction system deveioped multipie layer security redundancy spent necessary time resource test software ensure functionality security consumer focus group used deveiopment process make sure player opulent experience online future marketing effort wi aimed customer service attention company gaming transaction inc deveioper provider online game service online entertainment gaming industry company centrum licensed game portal k e n c destination oniine gambling property player may participate number gambling oniine gaming fixture foundation site course online version keno game keno us bail numbered thru every game house draw ball random display number screen called keno board ocated website object game piayer guess number house draw site also popuiar game including poker blackjack slot video game version tabie game gaming transaction inc part oniine gambiing industry said one fastest growing industry internet electronic gambling report forecast revenue reach biliion market statistic informa medium grp giobal revenue oniine gambiing wi reach bi ion biilion year according report informa medium grp say u wi generate percent online gambling revenue oo whereas europe wil generate percent north american oniine gambling revenue expected reach biliion year bi ion oo europe revenue wil grow billion year biilion oo oniine gambling revenue wi smailer asia pacific miliion year billion oo rest worid million year mi ion oo keno game one highest grossing product many north american government body pubiic gaming corporation easy piay quick profitabie keno become favorite gambiers want excitement lottery draw without wait weekiy offering combining sophisticated hardware software cutting edge encryption decryption technique keno com deveioped icensed system optimum method online gaming information within publication contains future looking statement within meaning section security act section b security exchange act statement express involve discussion respect prediction expectation belief pians projection objective goal assumption future event performance statement historica fact may future looking statement future ooking statement based expectation estimate projection time statement made involve number risk uncertainty couid cause actual result event differ materia presently anticipated future ooking statement action may identified use word project foresee expects anticipates estimate belief understands statement indicating certain action may could might occur future ooking statement based information currentiy avaiiabie subject number risk uncertainty factor couid cause ggts actua resuits performance prospect opportunity differ materialiy expressed impiied future ooking statement many microcap stock today company additiona risk factor raise doubt ability continue going concern ggts reporting company registered security act hence imited public information avaiiable company risk uncertainty factor include without imitation company growth expectation ongoing funding requirement specificaily company growth prospect scalable customer risk include company limited operating history company history operating loss consumer acceptance company use licensed technoiogies risk increased competition potentia need additional financing condition term financing consummated limited trading market company security possibie volatility company stock price concentration ownership potentia fluctuation company operating result publisher report represent information contained message state ail material fact omit material fact necessary make statement therein misieading information provided within report pertaining investing stock security must understood information provided investment advice publisher newsletter advises reader subscriber seek advice registered professional security representative deciding trade stock featured within report none materia within report shall construed kind investment advice solicitation many company verge bankruptcy lose al money investing stock pubiisher report registered investment expert subscriber view information herein egal tax accounting investment advice reference past performance company specially seiected referenced based favorabie performance company wouid need perfect timing achieve resuits exampies given assurance happening remember always past performance indicative future result thorough due diligence effort inciuding review company fiiings sec gov edgar online com avaiiabie shouid compieted prior investing al factua information report gathered pubiic source including imited company website company press release pubiisher discloses receipt fifteen thousand doilars third party officer director affiiiate shareholder company preparation oniine report aware inherent confiict interest resulting compensation due fact paid pubiication pubiisher report beiieves information reiiable make assurance accuracy compieteness use materia within report constitutes acceptance term wish stop future maiiings feel wrongfuliy placed membership piease go send biank e mai thanks subject stoxo yahoo com',
 'subject first delivery wheeler operating vance deal created entered sitara bob vance l taylor pm robert cotten hou ect ect cc julie meyers hou ect ect lisa hesse hou ect ect cynthia hakemack hou ect ect susan smith hou ect ect donald p reinhardt hou ect ect melissa graf hou ect ect subject first delivery wheeler operating bob following production line ticket created entered sitara based following counterparty meter volume price period global wheeler operating mmbtu gas daily nya fyi created submitted committed reserve firm ticket remaining term deal beginning month march additionally producer svcs deal tracked im wellhead portfolio attached gathering contract thanks vlt x forwarded vance l taylor hou ect pm esther buckley molly l carriere hou ect ect clem cernosek hou ect ect donna consemiu hou ect ect robert cook hou ect ect howard b camp hou ect ect lisa hesse hou ect ect nathan l hlavaty hou ect ect wayne e lightfoot hou ect james mckay hou ect ect mary smith hou ect ect steve hpl schneider hou ect ect melissa graf hou ect ect michael walter hou ect ect jill zivley hou ect ect mary jo johnson hou ee ee rita wynne hou ect ect lauri allen hou ect ect cheryl jones gpgfin enron enron reid hansen gco enron enron darron c giron hou ect ect neal winfree hou ect ect susan smith hou ect ect gary bryan hou ect ect gary hank hou ect ect donald p reinhardt hou ect ect vance l taylor hou ect ect david baumbach hou ect ect robert cotten hou ect ect brian riley hou ect ect jeff austin hou ee ee cynthia hakemack hou ect ect dawn c kenne hou ect ect lisa csikos hou ect ect j r fosdick gco enron enron carlos j rodriguez hou ect ect stephanie gomes hou ect ect pat clynes corp enron enron tom acton corp enron enron robert walker hou ect ect george weissman hou ect ect joanne harris na enron enron christy sweeney hou ect ect earl tisdale hou ect ect daren j farmer hou ect ect cc subject first delivery wheeler operating please see attached letter',
 'subject swift may vols sean fyi check purchase swift tailgate meter make sure nom correct quantity mary forwarded mary poorman na enron joan quick enron enronxgate pm carlos j rodriguez hou ect ect mary poorman na enron enron jackie young hou ect ect cc brian riley hou ect ect mike morris corp enron enron subject swift may vols may first month nom king ranch plant mmbtu',
 'subject meter variance ua clean daren vance two meter new unallocatable flow need purchase please respond deal number suggestion resolution clear soon possible mary enron katherine benedict ect pm mary poorman na enron enron fred boa hou ect ect aimee lannou hou ect ect cc subject meter variance ua clean hi guy please take look following meter showing variance ua report variance cleared please send e mail please try clear within next couple day thanks kathy benedict meter number variance meter type daily swing production month august logistics contact none volume mgmt contact anita luong meter number variance meter type daily swing production month august logistics contact none volume mgmt contact anita luong',

## TF-IDF Vectorizer

In [30]:
# Create the TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(max_features=100)
X = cv.fit_transform(corpus).toarray()

In [31]:
cv.vocabulary_

{'subject': np.int64(83),
 'enron': np.int64(24),
 'meter': np.int64(53),
 'flow': np.int64(28),
 'daren': np.int64(16),
 'please': np.int64(67),
 'daily': np.int64(15),
 'volume': np.int64(92),
 'gas': np.int64(33),
 'change': np.int64(8),
 'hpl': np.int64(38),
 'nom': np.int64(59),
 'see': np.int64(77),
 'attached': np.int64(2),
 'file': np.int64(26),
 'xl': np.int64(99),
 'time': np.int64(90),
 'know': np.int64(43),
 'go': np.int64(35),
 'week': np.int64(94),
 'like': np.int64(45),
 'following': np.int64(29),
 'need': np.int64(56),
 'get': np.int64(34),
 'let': np.int64(44),
 'first': np.int64(27),
 'would': np.int64(97),
 'could': np.int64(14),
 'www': np.int64(98),
 'com': np.int64(9),
 'also': np.int64(0),
 'one': np.int64(62),
 'email': np.int64(21),
 'back': np.int64(3),
 'make': np.int64(48),
 'deal': np.int64(18),
 'price': np.int64(69),
 'message': np.int64(52),
 'http': np.int64(39),
 'take': np.int64(85),
 'purchase': np.int64(72),
 'day': np.int64(17),
 'sale': np.int64(76),
 'march': np.int64(49),
 'today': np.int64(91),
 'mail': np.int64(47),
 'new': np.int64(58),
 'product': np.int64(70),
 'net': np.int64(57),
 'delivery': np.int64(19),
 'want': np.int64(93),
 'forwarded': np.int64(31),
 'texas': np.int64(86),
 'cc': np.int64(7),
 'mmbtu': np.int64(54),
 'nomination': np.int64(60),
 'stock': np.int64(82),
 'inc': np.int64(40),
 'month': np.int64(55),
 'april': np.int64(1),
 'service': np.int64(79),
 'company': np.int64(10),
 'system': np.int64(84),
 'call': np.int64(6),
 'information': np.int64(41),
 'business': np.int64(5),
 'number': np.int64(61),
 'help': np.int64(36),
 'statement': np.int64(81),
 'may': np.int64(51),
 'report': np.int64(74),
 'july': np.int64(42),
 'thanks': np.int64(88),
 'sitara': np.int64(80),
 'bob': np.int64(4),
 'pm': np.int64(68),
 'robert': np.int64(75),
 'hou': np.int64(37),
 'ect': np.int64(20),
 'production': np.int64(71),
 'ticket': np.int64(89),
 'contract': np.int64(12),
 'mary': np.int64(50),
 'gary': np.int64(32),
 'corp': np.int64(13),
 'farmer': np.int64(25),
 'contact': np.int64(11),
 'original': np.int64(64),
 'sent': np.int64(78),
 'question': np.int64(73),
 'per': np.int64(66),
 'energy': np.int64(23),
 'well': np.int64(95),
 'work': np.int64(96),
 'order': np.int64(63),
 'th': np.int64(87),
 'list': np.int64(46),
 'ena': np.int64(22),
 'pec': np.int64(65),
 'font': np.int64(30)}

N-Grams

In [32]:
# Create the TF-IDF with n-grams
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(max_features=100,ngram_range=(2,2))
X = cv.fit_transform(corpus).toarray()

In [33]:
cv.vocabulary_

{'subject enron': np.int64(85),
 'subject hpl': np.int64(87),
 'hpl nom': np.int64(50),
 'see attached': np.int64(82),
 'attached file': np.int64(4),
 'let know': np.int64(59),
 'enron com': np.int64(26),
 'texas utility': np.int64(94),
 'utility tu': np.int64(95),
 'com cc': np.int64(10),
 'cc subject': np.int64(6),
 'forward looking': np.int64(35),
 'looking statement': np.int64(61),
 'enron hpl': np.int64(29),
 'hpl actuals': np.int64(47),
 'teco tap': np.int64(92),
 'tap enron': np.int64(90),
 'hpl gas': np.int64(48),
 'gas daily': np.int64(39),
 'tenaska iv': np.int64(93),
 'vance taylor': np.int64(96),
 'robert cotten': np.int64(80),
 'cotten hou': np.int64(13),
 'hou ect': np.int64(45),
 'ect ect': np.int64(19),
 'ect cc': np.int64(17),
 'julie meyers': np.int64(56),
 'meyers hou': np.int64(63),
 'susan smith': np.int64(89),
 'smith hou': np.int64(83),
 'melissa graf': np.int64(62),
 'graf hou': np.int64(44),
 'ect subject': np.int64(24),
 'taylor hou': np.int64(91),
 'ect pm': np.int64(22),
 'ect robert': np.int64(23),
 'howard camp': np.int64(46),
 'camp hou': np.int64(5),
 'rita wynne': np.int64(79),
 'enron enron': np.int64(27),
 'gco enron': np.int64(42),
 'gary hank': np.int64(38),
 'ect pat': np.int64(21),
 'pat clynes': np.int64(71),
 'clynes corp': np.int64(9),
 'corp enron': np.int64(12),
 'george weissman': np.int64(43),
 'na enron': np.int64(65),
 'ect daren': np.int64(18),
 'daren farmer': np.int64(15),
 'farmer hou': np.int64(34),
 'enron enronxgate': np.int64(28),
 'jackie young': np.int64(55),
 'enron subject': np.int64(32),
 'subject meter': np.int64(88),
 'aimee lannou': np.int64(0),
 'lannou hou': np.int64(58),
 'subject fw': np.int64(86),
 'original message': np.int64(70),
 'enron cc': np.int64(25),
 'know question': np.int64(57),
 'oil gas': np.int64(69),
 'natural gas': np.int64(66),
 'hpl iferc': np.int64(49),
 'ami chokshi': np.int64(2),
 'http www': np.int64(54),
 'robert lloyd': np.int64(81),
 'lloyd hou': np.int64(60),
 'enron pm': np.int64(31),
 'ect enron': np.int64(20),
 'enron north': np.int64(30),
 'north america': np.int64(68),
 'america corp': np.int64(1),
 'www computron': np.int64(99),
 'computron com': np.int64(11),
 'would like': np.int64(98),
 'forwarded ami': np.int64(36),
 'chokshi corp': np.int64(8),
 'gas nomination': np.int64(40),
 'pm daren': np.int64(77),
 'please let': np.int64(76),
 'aol com': np.int64(3),
 'please call': np.int64(75),
 'deal ticket': np.int64(16),
 'farmer daren': np.int64(33),
 'fuel cotton': np.int64(37),
 'cotton valley': np.int64(14),
 'hplno xl': np.int64(51),
 'question please': np.int64(78),
 'href http': np.int64(53),
 'pefs pec': np.int64(73),
 'pec pec': np.int64(72),
 'gc cec': np.int64(41),
 'cec pec': np.int64(7),
 'hplo xl': np.int64(52),
 'mmbtu hsc': np.int64(64),
 'src http': np.int64(84),
 'pill pill': np.int64(74),
 'nbsp nbsp': np.int64(67),
 'width height': np.int64(97)}

In [35]:
import numpy as np
np.set_printoptions (edgeitems=30, linewidth=100000,
formatter=dict(float = lambda x: "%.3g" % x))

In [36]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0.467, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.449, 0, 0, 0, 0, 0.519, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0.142, 0, 0, 0, 0.21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.361, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.745, 0.5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0.721, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.693, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.613, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.296, 0, 0, 0, 0, 0.336, 0, 0.306, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0.0284, 0.0161, 0, 0, 0.025, 0, 0, 0.0355, 0.0509, 0, 0.0183, 0, 0.0335, 0.026, 0.682, 0, 0.0263, 0.0197, 0.0535, 0.0193, 0, 0, 0.111, 0, 0, ..., 0, 0.0244, 0, 0, 0, 0, 0, 0, 0, 0.0278, 0.0507, 0, 0.0183, 0.0786, 0, 0, 0, 0, 0, 0.0554, 0, 0.0545, 0, 0, 0, 0, 0.0744, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.164, 0, 0, 0, 0, 0.155, 0, 0.452, 0, 0, 0, 0, 0, 0, 0, 0.342, 0.272, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0.318, 0, 0, 0, 0, 0, 0.179, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.186, 0, 0.361, 0, 0, 0.219, 0, 0, 0, 0, 0.205, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.548, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.575, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.243, 0.22, 0.398, 0.317, 0, ..., 0.244, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.257, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0.467, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.449, 0, 0, 0, 0, 0.519, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0.137, 0, 0, 0, 0.0909, 0, 0, 0, 0, 0, 0, 0, 0, 0.104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.577, 0, 0, 0.398, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.192, 0, 0, 0, 0, 0.218, 0, 0.198, 0, 0.318, 0.24, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0.119, 0, 0, 0, 0, 0.118, 0, 0, 0, 0.103, 0, 0, 0.0735, 0, 0, 0.152, 0, 0.139, 0.215, 0.538, 0, 0, 0.0816, 0, 0.16, 0, 0, 0.0763, 0, 0, ..., 0, 0.101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.348, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.673, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.739, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.428, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.414, 0, 0, 0, 0, 0, 0, 0.428, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0.576, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.697, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.337, 0, 0, 0, 0, 0.382, 0, 0.348, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0.436, 0, 0, 0, 0, 0, 0.164, 0, 0, 0, 0, 0, 0, 0, 0, 0.186, 0, 0.256, 0, 0.33, 0, 0, 0.1, 0, 0.098, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.271, 0.125, 0, 0, 0, 0, 0, 0, 0, 0, 0.431, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0.363, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.275, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.613, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.422, 0.425, 0, 0, 0, 0],
       [0, 0, 0.522, 0, 0.206, 0, 0.174, 0, 0.542, 0, 0, 0, 0.383, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.243, 0, 0.199, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.198, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0.234, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.327, 0, 0.268, 0.427, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0.0226, 0, 0, 0, 0.16, 0.0302, 0, 0, 0.188, 0, 0, 0.133, 0, 0, 0.0689, 0, 0.158, 0.0488, 0.473, 0, 0.148, 0.0741, 0.0251, 0.0725, 0, 0, 0.139, 0, 0, ..., 0, 0.184, 0, 0, 0, 0.0228, 0, 0, 0.023, 0.105, 0, 0.342, 0, 0, 0, 0, 0, 0, 0.255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0.69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.724, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0.631, 0, 0.248, 0, 0.21, 0, 0.327, 0, 0.31, 0, 0.231, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.266, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.239, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0.397, 0, 0, 0.0931, 0, 0, 0, 0.108, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.24, 0, 0, 0, ..., 0, 0, 0.662, 0.397, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])